### ISSUE TITLE
Extend handling of abbreviated first names to more cases

### ISSUE THREAD

**Issue by markusstocker** [thor-project/OrcidResolver#1]
The implementation handles abbreviated first names such as in "Schindler, UH" using wildcards. Thus, the first name becomes U\* H*. However, it does not support other variants that are fairly common, namely "U.H.", "U. H.", or "U.".

**Comment by uschindler** [comment]
This is a good idea. The reason for the current behaviour is: PANGAEA always uses capital letters only: "Schindler, UH" without whitespace. We can of course extend that. That may need a bit more complicated regular expressions, but basically it is doable. Maybe we should make the expansion configurable (so users can also swtch it off).

**Comment by markusstocker** [comment]
Fixed. The option for configuration is left to a future issue.

**Comment by uschindler** [comment]
Looks good! Thanks for committing this.
